base_url = "https://rrwright.com"
title = "Ryan Wright"
description = "The personal page of Ryan Wright: Philosopher-CTO, researcher, software engineer, inventor of the streaming graph"
default_language = "en"
compile_sass = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
smart_punctuation = true

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[[taxonomies]]
name = "tags"

[extra]
author = "Ryan Wright"
